### ISSUE TITLE
Availability of updated versions

### ISSUE THREAD

**Issue by sarthakpati** [conda-forge/dicomweb-client-feedstock#12]
### Comment:

Hi,

There are 2 new versions of this out:

- https://github.com/ImagingDataCommons/dicomweb-client/tree/v0.59.2
- https://github.com/ImagingDataCommons/dicomweb-client/tree/v0.59.3

But they don't seem to be available through conda. Is there any plan to make these available?

**Comment by acaprez** [comment]
Updated to v0.59.3 [here](https://github.com/conda-forge/dicomweb-client-feedstock/pull/14).
